"""empty message

Revision ID: 598cfa6dcffc
Revises: 
Create Date: 2018-03-15 16:08:58.225290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598cfa6dcffc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_recor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=200), nullable=False),
    sa.Column('real_name', sa.String(length=200), nullable=False),
    sa.Column('id_card', sa.String(length=100), nullable=False),
    sa.Column('age', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.Column('weight', sa.String(length=200), nullable=False),
    sa.Column('height', sa.String(length=100), nullable=False),
    sa.Column('remark', sa.String(length=250), nullable=False),
    sa.Column('consultant_id', sa.String(length=250), nullable=False),
    sa.Column('create_at', sa.Integer(), nullable=False),
    sa.Column('update_at', sa.Integer(), nullable=False),
    sa.Column('outer_id', sa.Integer(), nullable=False),
    sa.Column('outer_consultant_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telephone', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('health_recor')
    # ### end Alembic commands ###
